---
title: "abxD01 Paper"
author: "Alyxandria Schubert"
date: "February 26, 2015"
output: html_document
---



# Abstract




# Introduction

The microbiome, or the diverse community of microorganisms living in and on the body, has an integral role in deterring pathogen colonization and infection. This native protection by the microbiome from invasive pathogenic species is termed colonization resistance. It is well established that the gut bacterial microbiome is critical in the hosts’ defense against the pathogen Clostridium difficile. When this indigenous community is perturbed, this often leads to a loss of resistance. This is especially important in many hospital settings where patients are not only exposed to various types and degrees of perturbations, such as antibiotics, diet changes, chemotherapy, but also exposed to the environmental C. difficile spores. Among hospital-acquired infections in the United States, C. difficile infections (CDI) are the number one reported and are responsible for 14,000 deaths a year. It is not completely understood how different perturbations affect subsequent colonization resistance, nor do we have a comprehensive view of the taxonomic changes associated with a loss in colonization resistance.

There is a need for more knowledge about interactions between members of the community. Know that fmts work [anna’s paper], but don’t know why, except that you recover the diversity and are receiving an established community already that works. Individual probiotics have not worked with complete success [dendukuri 2005], whereas studies find that combinations of bacteria often work better than by themselves [lawley, pamer, stein, hickson 2007]. It’s also common for bacteria to change their behavior in the context of other bacterial species [Crost 2010, quorum sensing-biofilms, recognizing fellow bacterial species vs killing others, synergistic effects (sieuwerts 2010)]. Understanding the scope of relationships between bacteria in a community is necessary to learn about its response, in concert with its host, to perturbations including antibiotic-induced, pathogen invasion, probiotics doses, and diet changes, etc. 

The purest way of studying these bacterial interactions is by characterizing them in the context of their whole biome [ecology citation?]. [examples of papers showing microbiomes response to antibiotics in the context of CR]

These observed changes in response to perturbation can be used to inform models and networks to predict future responses (stein, Gordon diet paper) and characterize bacterial interactions (psoriasis/Schubert, sparCC paper). These methods are advantageous in that they can be refined to determine probiotic prophylactics or treatments based on an individual patient’s gut microbial needs.  

The purpose of this investigation was to test the effects of an array of perturbations on microbiome CR levels against C. difficile.  We then used this information to design microbiome-based models for estimating pathogen colonization levels. Through the administration of various antibiotic regimens, we altered the murine gut microbiota and observed these changes using 16S rRNA sequencing. The resultant gut communities were then challenged with C. difficile spores. Through correlation and random forest analysis of the starting communities with the subsequent level of C. difficile colonization, we built linear models to predict C. difficile colonization levels based on a subset of the microbiota. We used experimental data to test the ability of the model. 

Though we are limited in a resolution at the strain and species level, we have identified groups of related species with antagonistic relationships with C. difficile colonization. We identified several models with equally robust quality statistics and observed that across the top models a subset of 5 species were consistently present. These findings __


# Materials and Methods

## Animal Care

We used 5-8 week old C57Bl/6 mice for all our experiments. These mice were housed in our SPF room in the animal facility at the University of Michigan. All animal-related protocols and experiments were approved by the University Committee on Use and Care of Animals at the University of Michigan. 

## Antibiotic Administration

Mice were administered one of seven different antibiotics, including cefoperazone, vancomycin, metronidazole, streptomycin, ciprofloxacin, ampicillin, and clindamycin. The route of administration depended on the specific antibiotic. Cefoperazone (either 0.5mg/ml, 0.3mg/ml, or 0.1mg/ml), vancomycin (0.625mg/ml, 0.3mg/ml, or 0.1mg/ml), streptomycin (5mg/ml, 0.5mg/ml, or 0.1mg/ml), metronidazole (0.5mg/ml), and ampicillin (0.5mg/ml) were all administered in the mouse drinking water for 5 days. Ciprofloxacin (10 mg/kg) was administered via oral gavage, and clindamycin (10 mg/kg) was administered via IP injection. All antibiotic treated mice were given 24 hours of recovery on regular drinking water prior to C. difficile challenge. 

## C. difficile Preparation and Challenge

In all our experiments we used C. difficile strain 630Δerm [cite dena lyras]. The spores used were prepared from a single large batch made following previously established protocols [cite paul?]. Spores were quantified within the week prior to C. difficile challenge for each experiment [established protocol I can cite?]. Spores were quantified by boiling a small volume at 65°C for 20 minutes to kill off residual vegetative cells. The volume was then diluted and plated on TCCFA plates. These were incubated at 37°C anaerobically overnight. The next day C. difficile colony forming units (CFU) were counted and the concentration of spores in the working stock was back calculated. On the day of challenge, C. difficile spores, at a final concentration of 103, were administered to mice via oral gavage. Immediately following this challenge, the remaining C. difficile inoculum was diluted in a series and plated to confirm the correct dosage. 

## Sample Collection and Plating 

Fecal samples were freshly collected for each mouse immediately prior to the administration of any antibiotic, during any antibiotic recovery days, and days 0 and 1 post C. difficile challenge. Each fecal sample on day 1 was weighed and diluted under anaerobic conditions with anaerobic PBS 1:10 based on pellet weight. A dilution series was then plated onto TCCFA plates [cite plates] and incubated at 37°C anaerobically overnight. The colony forming units (CFU) were counted and calculated the subsequent day. 

## DNA Extraction and Sequencing

Total bacterial DNA was extracted from each untreated and day 0 stool sample using the MOBIO PowerSoil®-htp 96 Well Soil DNA Isolation Kit. Sequencing preparation and sequencing was carried out as previously described (Kozich JJ et al. 2013). Briefly, the V4 region of the 16S rRNA gene was amplified, purified, and pooled in equimolar concentrations. These libraries were then mixed with Illumina-prepared PhiX control libraries. Sequencing was performed using Illumina’s MiSeq platform to produce paired 250-nt reads. Mock/error/error of run?

## Sequence Curation 

These sequences were curated using mothur as previously described (Kozich JJ et al and Schloss PD et al). The full pipeline is also demonstrated online at the mother website (http://www.mothur.org/wiki/MiSeq_SOP). Sequences were binned into operational taxonomic units (OTUs) using a 3% dissimilarity cutoff. Taxonomic assignments were determined by using a naïve Bayesian classifier with the Ribosomal Database Project (RDP) training set (version 9) requiring an 80% bootstrap confidence score. In order to avoid biases due to uneven sampling, samples were normalized to 1,625 sequences per samples [Schloss, reducing effects]. For those samples with more than 1,625 sequences per samples, the range was __, the mean was __, the median was __, the median absolute deviation was __. All 16S rRNA gene sequence data and the MIMARKS table are available at __. 

## Statistical Analysis & Modeling 

Using data from the original antibiotic treatments groups, OTUs were selected for addition into the model following several criteria. First all OTUs were present in abundance at an average of 1% in at least one experimental group. 

All statistical analyses were conducted using R version 3.1.2. 


# Results

## Levels of colonization resistance are associated with the initial structure of the gut microbiota. 

In mouse models of CDI, the baseline, untreated murine microbiota is completely resistant to C. difficile colonization. It was previously shown that C57Bl/6 mice treated with cefoperazone [], clindamycin [], or clindamycin in combination with a five antibiotic cocktail [] all have decreased resistance against this pathogen. To further characterize structural shifts in the microbiota associated with this loss of protective function, we chose a panel of seven representatives from six classes of antibiotics (Table 1) to differentially alter the microbiota and assess their resistance to C. difficile colonization. 16S rRNA gene sequencing of the fecal communities sampled at the time of C. difficile inoculation revealed distinct and reproducible microbiota structures (Figure 1). The community structures of the beta-lactam-treated mice (i.e. cefoperazone and ampicillin) were not significantly different from each other (AMOVA, p=0.36). Clindamycin-treated microbiotas were significantly different from all other treatment groups (AMOVA, p=0.001) and were characterized by the predominance of Enterobacteriaceae. Of all groups significantly different from the untreated microbiota, the levels of Enterobacteriaceae increased with all treatments except with streptomycin. Vancomycin-treated communities saw the largest bloom in Akkermansia. In addition, the ciprofloxacin-treated microbiota were the only group that was not significantly different from untreated mice (AMOVA, p=0.09). Subsequently, 24 hours after inoculation C. difficile was undetectable in the untreated mice or the ciprofloxacin-treated mice; however it had successfully colonized the mice in all of the other treatment groups to similarly high levels (107-108 CFU/g) (Figure 1). We calculated the diversity of all of the communities using the Inverse Simpson (Supplemental Figure 1) and Shannon indices (data not shown) and observed a significant negative correlation with subsequent C. difficile colonization (both p<0.001). These results suggest that multiple microbiota structures are capable of being colonized by C. difficile and that diversity may be an important factor in resistance to invasion.

## Correlation analysis reveals potentially protective bacteria. 

To identify bacterial taxa that could be associated with resistance or susceptibility to C. difficile, we measured the correlation between the relative abundance of each species-level OTU on the day of inoculation with the level of C. difficile colonization 24 hours later across all treatment groups (Figure 2). Of the significant OTUs (p<0.05) with an average abundance greater than 0.1%, OTUs with negative a correlation were associated with providing resistance against C. difficile (N=40) and those with a positive correlation were associated with susceptibility (N=7). Among various bacterial families, three were consistently negatively correlated with C. difficile colonization: Porphyromonadaceae (ρaverage= -0.63), Lachnospiraceae (ρaverage= -0.51), Ruminococcaceae (ρaverage= -0.53). OTUs from the Proteobacteria phylum had strong positive relationships with C. difficile colonization. These included OTUs associated with the Pseudomonas (ρ= 0.31) and Escherichia (ρ= 0.56) genera. Other notable OTUs that were found at the extremes of the distribution of correlation scores included those affiliated with the genus Lactobacillus (family Lactobacillaceae; OTU23, ρ= -0.73), Alistipes (family Rickenellaceae; OTU20, ρ= -0.78), Enterorhabdus (phylum Actinobacterium, family Coriobacteriaceae; OTU29, ρ= -0.70), and Streptococcus (family Streptococcaceae; OTU78, ρ= 0.36). Overall, these results suggest that several larger groups of related OTUs, particularly within the Firmicutes and Bacteroidetes phyla, may participate in colonization resistance against C. difficile, while members of the Proteobacteria phylum may be involved in susceptibility.

## Smaller perturbations of the microbiota result in maintenance of colonization resistance. 

transition
Because most of our original treatments resulted in similarly high levels of C. difficile, we hypothesized that applying smaller antibiotic perturbations to the microbiota would result in reduced sensitivity to C. difficile, as we observed in the ciprofloxacin treated mice. To test this, we titrated the doses of cefoperazone, streptomycin, and vancomycin given to mice (Supplemental Table 1). Colonization levels decreased significantly in all mice receiving titrated doses in support of our hypothesis. C. difficile levels were significantly different between all titration groups within the cefoperazone (p<0.03) and streptomycin treated microbiotas (p<0.01), displaying a greater range of colonization resistance profiles (Figure 3). Next, we hypothesized that the populations we previously identified as being associated with protection against colonization would be elevated in the mice with decreased colonization and those associated with susceptibility would be less abundant.

The titrated antibiotic doses clearly resulted in distinct community structures that were variations of the original dose (Figure 3). The cefoperazone titrations resulted in a shift in dominance from the Bacteroidetes to the Firmicutes phylum with increasing antibiotic dose. Most notable was the increase in OTUs associated with resistance including the Porphyromonadaceae and Alistipes and a reduction in OTUs associated with susceptibility including members of the Proteobacteria, Clostridium, and Staphylococcus. The relative abundance of other OTUs associated with protection including the Lactobacillus, Lachnospiraceae, and Ruminococcaceae did not change as expected based on the initial correlation analysis; however, these OTUs were present at levels similar to the untreated mice. The streptomycin titrations did not result in profound shifts in the overall community structure, but did yield increased resistance. Rather, there were individual populations that were gained or lost across the gradient. Notably, mice receiving the lowest dose retained significantly higher levels of Alistipes and Anaeroplasma (p<0.05), which we previously found to be strongly associated with colonization resistance. The relative abundances of the Porphyromonodaceae, Lachnospiraceae, Ruminococcaceae were unchanged, but were present at similarly high levels to those found in the untreated mice. Although the vancomycin titration yielded a number of large changes in the abundance of individual populations, there was no recovery of colonization resistance. The relative abundance of many of the populations associated with resistance (Porphyromonadaceae, Lachnospiraceae, Anaeroplasma) increased with decreased vancomycin dosage; however, with the exception of the Lactobacillus populations, they did not reach the levels observed in the untreated mice. In addition, all of the vancomycin-treated mice had high levels of OTUs affiliated with the Akkermansia and Enterobacteriaceae. Together, these results suggest that individual populations are not sufficient to provide colonization resistance. Rather, resistance is likely a product of the overall composition of the community.

## Allowing recovery of specific bacteria restores colonization resistance. 

Several antibiotic perturbation studies have demonstrated that given time perturbed communities can return to a “healthy” state in which resistance to C. difficile is restored []. For each antibiotic treatment, a control group of mice receiving antibiotics without inoculation of C. difficile was maintained. The microbiota’s of animals treated with metronidazole underwent a drastic shift in the microbiota structure with an additional 5 days of recovery. We observed changes in relative abundance of several OTUs that we previously observed had strong relationships with subsequent C. difficile colonization (Figure 3). Notably there were significant increases (p<0.05) in overall abundance of the levels of Porphyromonadaceae, Ruminococcaceae, and Lachnospiraceae to levels similar to untreated microbiota, and significant decreases (p<0.05) in levels of Enterobacteriaceae. Based on these changes, we hypothesized that delaying C. difficile challenge to allow these potentially important changes in microbiota structure to occur would lead to a decrease in colonization. On Day 1 post challenge of these recovered mice, we observed a significant decrease in C. difficile level of CFU/g feces (p<0.0001). These results strengthen the importance of Porphyromonadaceae, Lachnospiraceae, Ruminococcaceae, and Enterobacteriaceae in setting up the right environment of negatively and positively correlated bacteria to affect the outcome of C. difficile colonization. 

Additionally, we assessed the resistance of ampicillin treated mice given five extra days of recovery prior to C. difficile challenge. The shift in the microbiome with ampicillin recovery was not as prounounced as seen with recovery of metronidazole treated animals. These communities had significantly reduced levels of bacteria correlated with C. difficile protection, including Bacteroides, Alistipes, and Ruminoccocaceae compared with untreated animals (p<0.05). Importantly, the level of Enterobacteriaceae was not significantly reduced with additional recovery time. Given the smaller changes towards a protective baseline state, it was not all that surprising that we were unable to detect significant changes in subsequent C. difficile levels. 

## Modeling to predict C. difficile colonization outcomes. 

Given our ability to make general predictions of C. difficile colonization based on the microbiota, we next designed a model to calculate expected colonization levels given the relative abundance of a subset of OTUs. Combining the three datasets (Table 1, Supplemental Table 1 and 2), we set a 1% relative abundance threshold, eliminating OTUs that on average were not present at this level in at least one of the 16 experimental groups. In total, there were 44 OTUs utilized for building a random forest regression model. This model fit the data with an R2 of 0.98 (Figure 5A). We identified OTUs that contributed most to increased accuracy of the model using random forest’s feature selection (Figure 5B). Many of the top contributing OTUs includes members of the Porphyromonadaceae family, Alistipes, Lachnospiraceae, Lactobacillus, and Escherichia taxa. The relationship between these OTUs and C. difficile is shown in Figure 5C. Escherichia had the largest positive correlation with C. difficile levels of any bacterial species.  This finding was consistent across susceptible antibiotic treated communities except for streptomycin treated communities, which altogether lacked Enterobacteriaceae spp. OTUs 3 and 39 (Porphyromonadaceae and Lachnospiraceae, respectively), were the two most important features in accurately predicting subsequent C. difficile levels. In fact, a model built with only these two features was able to account for 79% of the variance observed. Together these results suggest that colonization resistance is likely conferred by porphyromonadaceae, Alistipes, and lachnospiraceae and a loss in these bacteria, concurrently with a gain of Escherichia, can result in increased susceptibility to infection.  



# Discussion

-community effect—have other things to compensate—highlight examples –streptomycin blue triangles—where low lachno but no cdiff so what else is protecting? Not one otu that explains it all… just cus low levels doesn’t screw you, also see recovered points in 5C-angela, sonnenburg-need other thingsssss
  -fig2—there are like larger groups in protection/susceptibility
	-combo of loss of good bugs, and gain of bad—a model of infection
-tie back to mbio paper, with enterobacteriaceae they are screwed
-modeling—not much done for CDI, link back to humans, shows we could model risk as they come in—put towards end with the larger picture
We designed statistical models based on a data set of varied antibiotic perturbations of the murine microbiota and their subsequent CR levels against C. difficile. Though antibiotic administration induced unique microbiota structures, colonization resistance was similarly low against C. difficile. 
These models incorporated all combinations of top candidate species-level OTUs. We then tested our top model’s ability to use new abundance information on a specific subset of the microbiota to predict the subsequent C. difficile colonization level, which was experimentally validated. These results greatly expand our knowledge of various perturbations and their subsequent effects on microbiota structure and function (colonization resistance ability). Furthermore modeling important/key bacterial subsets of the community we can build models to assess CDI risk.

Through our perturbation experiments we identified a panel of bacteria with either strong positive or negative relationships with subsequent levels of C. difficile colonization. A large number of Porphyromonadaceae, Lachnospiraceae, Ruminococcaceae, and Clostridia, as well as Alistipes were found to have strong potential resistance abilities against C. difficile. Conversely, several members of the Proteobacteria phylum, including Pseudomonas, Streptococcus, and especially E. coli have strong potential positive impacts for C. difficile colonization. These results were supported by their strong correlation values supported across several antibiotic regimens. They are also supported through experiments in which the original doses of cefoperazone, streptomycin, and (vancomycin) were titrated to alter the overall abundances but not membership of the community from the starting dose, as has been observed previously (Sekirov). These subtler structural changes allowed for greater range of colonization levels of C. difficile as well as further/fine-tuned support for our original results. Furthermore, by allowing a known change to occur in important bacterial populations within metronidazole treated mice, we were able to reduce the level of colonization by C. difficile. Lastly we showed their importance through modeling techniques that statistically confirm these results. 

Previous work characterizing the microbiome’s of human and mouse hosts in the context of CDI provide glimpses into potentially protective and alternatively susceptible community structures, i.e. which bacteria are present and their abundance. Cross-sectional investigations have characterized the microbiota of patients in the hospital with and without a C. difficile infection (CDI) and compared to healthy controls. These studies found patients with C. difficile tended to have a reduction in numbers of Clostridiales Incertae Sedis XI (Vincent et al), Lachnospiraceae, Ruminococcaceae, and Bacteroides (Schubert et al). These studies however lack the baseline healthy state of the microbiota, which preclude them from assessing risk of C. difficile. Murine models of CDI have the advantage of observing the specific changes that occur before and after controlled perturbations and the introduction of C. difficile. Communities with low levels of CR were associated with blooms in either Lactobacillaceae (cefoperazone-induced) (Theriot, 2014, bassis, 2014), Proteobacteria (induced by either clinda+5abx cocktail, clinda alone, or tigecycline) (Reeves, 2011, Buffie, 2011, Bassis 2014). Lachnospiraceae is associated with resistance to C. difficile infection (Reeves 2011) and has been directly shown to decrease colonization through mono-colonization studies in germfree mice (Reeves 2012).

Even fewer studies attempt to model these observational changes in the microbiome following perturbation. Using the time series data gathered from the C. difficile challenge of clindamycin-treated mice (Buffie 2011), a Lotka-Volterra dyamics-based framework was built which incorporates both time and accounts for external perturbations (Stein 2013). They identified a subset of their network, containing Blautia, Akkermansia, and Coprobacillus, as having a negative relationship with C. difficile, while alternatively Enterococcus had a positive relationship. 

------------------

o  How relates to other studies
•	Antonopoulos et al-reproducible community dynamics
•	Antunes et al (finlay)—abx treatment on intestinal metabalome
•	Sekirov—antibiotic induced perturbations of intestinal microbiota
•	 “Change in the compostion alone of the intestinal microbiota (in the absence of significant changes in total numbers of intestinal microbes) prior to Salmonella serovar Typhimurium infection was sufficient to make mice more susceptible to Salmonella serovar Typhimurium, indicating that different subsets of the microbiota may play protective roles or enhance susceptibility to enteric infections.”
•	Streptomycin and vancomycin doses were administered to mice prior to challenge with another gastrointestinal pathogen Salmonella enterica serovar Typhymurium (Sekirov 2008).  This study showed ___. Changes in community composition were dose dependent. 
•	Strep increases bacteroidetes (CFB), vanc increases firms and then proteo (with increasing dose)
•	Reeves/theriot/robinson—clindamycin/cef/cocktail/antbiotic administration alters the community structure
•	Croswell—prolonge impact of abx on intestinal microbial ecology salmonella
•	Rea- effect of  broad and narrow spectrum antimicrobials
•	Ferreira—intestinal microbiota plays a role in salmonella induced colitis
•	Reeves with clone libraries and cef
•	Theriot?—at least the metabolome paper—before and after with metabolites and cef, also does she look at anything taxonomically? yup

Many of the relationships we observed in our study between specific bacteria and C. difficile are supported in the literature. –see my comments in this section
Within the Porphyromonadaceae, only OTU505 had a significant positive relationship with subsequent C. difficile colonization (ρ= +0.21), which by blastn shares 99% identity with Coprobacter fastidiosus. Similarly within the Lachnospiraceae family, only one OTU had a positive relationship with C. difficile colonization (OTU174, ρ= +0.22). The Lachnospiraceae group also contained an OTU that had an exceptionally strong negative correlation (OTU39, ρ= +0.77). The Clostridia class was largely composed of the order Clostridiales (n=6), of which only one had a positive relationship with C. difficile colonization (OTU154, ρ= +0.26). 


Several broader groups of bacteria can work together (in some combination) to provide CR …possible that proteobacteria in general are bad …These results indicate that many related species within the larger/broader bacterial groups may be able to serve in providing colonization resistance against C. difficile.
Other taxons in Figure 3 had more species specific correlations. For instance the Actinobacteria phylum included Enterorhabdus (OTU29, ρ= -0.70), Coriobacteriaceae (OTU50, ρ= -0.50), Bifodbacterium (OTU22, ρ= -0.34), Actinomyces (OTU58, ρ= +0.23). The Lactobacillales group is divided into two negatively correlated Lactobacillus OTUs (OTUs 23, 21, ρ= -0.73, -0.40 respectively) and two positively correlated Streptococcus OTUs (OTUs 78, 79). Similarly, the Bacteroidales group included species at both extremes, for example, an Alistipes (OTU20, ρ= -0.78) and a Bacteroides species (OTU44, ρ= +0.34). [END sent, all the other bad bugs look more like random smaller level taxonomic classification divisions, as in it’s a genus/species level effect type deal] 
--functional redundancy? Across related large groups like porphyros?
--mostly Firmicutes—better competitors with cdiff? Because similar nutrients resources? 
Also functional redundancy with a highly diverse community… not just about who possibly but also ab being diverse—emphasizes community as a whole

OTU39—Eubacterium ventriosum (94%), eubacterium rectale (93%), roseburia intestinalis/hominis/faecis (93%) (positively correlated to differences observed in discordant MZ twins for BMI—more abundant in higher BMI siblings… these are all butyrate producers, also capable of degrading fiber)
	FOS—fructooligosaccharides produced by degredation of inulin or polyfructose

Inulin and fructo-oligosaccharides have divergent effects on colitis and commensal microbiota in HLA-B27 transgenic rats.
Abstract
Modulation of intestinal microbiota by non-digestible carbohydrates may reduce inflammation in inflammatory bowel disease (IBD). The aim of the present study was to assess the effects of inulin and fructo-oligosaccharides (FOS) on intestinal microbiota and colitis in HLA-B27 transgenic rats, a well-validated rodent model for IBD. In this study, 4-week-old rats were fed 8 g/kg body weight inulin or FOS for 12 weeks, or not. Faeces were collected at 4 and 16 weeks of age; and caecal samples were collected at necropsy. The effects of inulin and FOS on chronic intestinal inflammation were assessed using a gross gut score, histology score and levels of mucosal IL-1β. Intestinal microbiota were characterised by quantitative PCR and denaturing gradient gel electrophoresis. Colitis was significantly reduced in all FOS-fed rats compared to the control diet, whereas inulin decreased chronic intestinal inflammation in only half the number of animals. Quantitative analysis of caecal microbiota demonstrated that inulin increased the numbers of total bacteria and the Bacteroides-Prevotella-Porphyromonas group, FOS increased bifidobacteria, and both fructans decreased Clostridium cluster XI. In the faecal samples, both inulin and FOS decreased total bacteria, Bacteroides-Prevotella-Porphyromonas group, and Clostridium clusters XI and XIVa. FOS increased Bifidobacterium spp., and mediated a decrease of gene copies of Enterobacteriaceae and Clostridium difficile toxin B in faeces. SCFA concentrations in the faecal and caecal samples were unaffected by the diets. In conclusion, FOS increased the abundance of Bifidobacterium spp., whereas both fructans reduced Clostridium cluster XI and C. difficile toxin gene expression, correlating with a reduction of chronic intestinal inflammation.


Any interesting points about the results?  Mechanisms? Competition—ask matt if they are good?  Proteobacteria could definitely play a role in susceptibility—creating an environment fit for cdiff… what ways could all those other bugs be making a bad environment for cdiff? Using up bile acids/germinants..,  with those bugs gone freeing up sugars, … maybe connecting a lot more to some of caseys metabolome paper, and how mine would fit that

o	Limitations
•	No smaller intervals? Of cdiff levels, or changes in microbiota
•	Porphyromonadaceae is more prevalent in mice… so might not be as relevant for humans
•	Different strains of cdiff have different microbiota requirements to protect?
•	Doesn’t get at function… ?
•	Collect more data to continue to improve our microbiome modeling abilities, 


o	Contribution to the field, positive spins
•	PROBIOTICS
•	Possible global effects? CR against other GI pathogens?
•	clinical applications—PCR diagnostic for risk


The final paragraph should highlight the main conclusion(s), and provide some indication of the direction future research should take. (for and I and I mention host)
-therapeutic: continuously supply probiotics  while lowering inflammation of the host (get host side back to normal state in tandem, via drugs? diet)… so attack the issue of CDI from both the microbiota end and host end… microbiota-host-pathogen triangle… …squeeze it out (eg. clindamycin clearance? If compared pathology of host at diff days along 10d for clindamycin vs cef/met/amp (these other ones that are high in cdiff coloniz), is host or toxin diff?... why does clinda clear after being CDhigh but no other ABX?)



The human microbiome is complex; it has been observed that there is no identifiable “core” microbiome that all humans share (Turnbaugh 2009). It’s been observed that there is a high level of interindividual variation among healthy individuals’ microbiomes (Costello 2009). Thus the definition of a healthy microbiome is one that encompasses a wide range of microbiota structures, each one evolved with their host. It’s highly likely there is no one size fits all solution for the treatment or prevention of CDI. Thus characterizing the relationships within the microbiome are important in the context of a community. Need more studies that look at the level of the community as a whole in CR over the effect of single bugs.  Examples of papers looking at combinations/subsets of bacteria in CR


	It makes sense that many bacteria would play a role in colonization resistance and that it is more about the community composition as a whole given that interindividual differences is so great.  Two people share no more than __% of their microbiomes.  They are unique to individuals and yet all these different profiles of microbiotas are capable of colonization resistance.  People do not get C. difficile infections without first being exposed to some major purturbation of their microbiome, namely antibiotics.  Thus many structures of the microbiome, and many distinct bacterial populations must be capable of contributing to resistance.  Identifying/cataloguing a comprehensive profile of those bacteria with potential roles in CR would be an initial step towards personalized/individualized treatments with known mixtures of protective bacteria. 
Bacteria within a community setting may act differently in the context of other bacterial species. 



[using this time model for the metro… I wonder if it doesn’t work because of the time difference in the amount of recovery time? I’m picturing sort of an echo/ripple effect where at first the waves, or changes, are really large and then over time that rate of change of the community slows and the changes less pronounced/smaller. In this context the metro communities were at a stage farther along in the echo, meaning changes not happening as fast. Whereas the measurements we’ve taken and are using to make predictions are from the community at a time when you expect more/bigger/faster changes. So then the results are calculated assuming one rate but actually in a different (slower). 
By this image, the initial strength of the perturbation matters too.] 


--also somewhere, ecoli are typically on avg (__% of the community, typically wayyyy outnumbered… whats the avg relabund of all those CR OTUs in an untreated mouse, how does that compare to the abundance of those bacteria I’ve implicated in –CR) …point is that Proteobacteria are usually outnumbered… don’t have a chance, gut is suited to bact/firm (which not surprisingly make up the major players in CR).. I bet those other outlier bad bugs are also in low abund in untreated mice (?). but when the gut environment changes for w/e reason, can give those rarer bad ones/proteo/esp e. coli a chance to take hold. They could just be individually opportunistic or work synergistically with cdiff. If individually opportunistic, it might be that they are facing pretty much a common enemy which is the lach/rum/clos/porphs and end up having similar techniques/niches as a result of that common enemy. Working synergistically—eg. b. theta sialidase where it cleaves off resources for cdiff.

